baseURL = "https://patasicarbon.github.io/"
languageCode = "en-us"
title = "Patasi Carbon Frames Repairs"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.jpg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Patasi Carbon Frames Repairs"

  [params.homepage_meta_tags]
    meta_description = "Patasi Carbon Frames Repairs Forks Repairs Cranks Repairs"
    meta_og_title = "Patasi Carbon Frames Repairs"
    meta_og_type = "website"
    meta_og_url = "https://patasicarbon.netlify.app"
    #meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Patasi Carbon Frames Repairs"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
